# Generated by Django 4.2.30 on 2026-05-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueItemDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('item_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_daily', to='venues.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'total_revenue'], name='metrics_ven_date_84309e_idx'), models.Index(fields=['venue', 'date', 'total_revenue'], name='metrics_ven_venue_i_a84a6a_idx')],
                'unique_together': {('venue', 'date', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='VenueHourlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DateTimeField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('void_count', models.IntegerField(default=0)),
                ('refund_count', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_metrics', to='venues.venue')),
            ],
            options={
                'ordering': ['hour'],
                'indexes': [models.Index(fields=['venue', 'hour'], name='metrics_ven_venue_i_3c9786_idx'), models.Index(fields=['hour'], name='metrics_ven_hour_109385_idx')],
                'unique_together': {('venue', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='VenueDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('void_count', models.IntegerField(default=0)),
                ('refund_count', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='venues.venue')),
            ],
            options={
                'ordering': ['-total_sales'],
                'indexes': [models.Index(fields=['date'], name='metrics_ven_date_5ed76a_idx'), models.Index(fields=['date', 'total_sales'], name='metrics_ven_date_b597c4_idx')],
                'unique_together': {('venue', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sales_drop', 'Sales Drop'), ('void_spike', 'Void Spike'), ('refund_spike', 'Refund Spike')], max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='metrics_ale_is_acti_62b1d9_idx'), models.Index(fields=['venue', 'is_active'], name='metrics_ale_venue_i_b487d8_idx')],
            },
        ),
    ]
