# Generated by Django 4.2.30 on 2026-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_venue_i_bc3608_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_type_01400b_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sale'), (2, 'Void'), (3, 'Refund')], db_index=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['venue', 'created_at'], name='transaction_venue_i_2bc535_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'created_at'], name='transaction_type_a267f0_idx'),
        ),
    ]
