# Generated by Django 4.2.30 on 2026-05-14 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_venue_i_2bc535_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_type_a267f0_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['venue', 'timestamp'], name='transaction_venue_i_bc3608_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'timestamp'], name='transaction_type_01400b_idx'),
        ),
    ]
